version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=pets
  api:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    environment:
      - DATABASE_URL=postgres://root:root@db:5432/pets
    ports:
      - "8000:8000"
    depends_on:
      - db
  